# Generated by Django 4.2.15 on 2024-09-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price_increase_per_unit',
            field=models.FloatField(default=0.0),
        ),
    ]
